# Generated by Django 5.1.1 on 2024-09-16 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentDormitory', '0002_room_alter_student_options_alter_student_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='ФИО')),
                ('post', models.TextField(verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Персонал',
                'verbose_name_plural': 'Персонал',
            },
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='number_room',
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.TextField(default='1', verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.TextField(default='ИСТБ-22-2', verbose_name='Группа'),
        ),
        migrations.CreateModel(
            name='DutySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentDormitory.room')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentDormitory.student')),
            ],
            options={
                'verbose_name': 'График дежурств',
                'verbose_name_plural': 'График дежурств',
            },
        ),
        migrations.CreateModel(
            name='RepairRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата создания')),
                ('description', models.TextField(verbose_name='Описание проблемы')),
                ('status', models.TextField(verbose_name='Статус заявки')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentDormitory.room')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentDormitory.staff')),
            ],
            options={
                'verbose_name': 'Заявка на ремонт',
                'verbose_name_plural': 'Заявки на ремонт',
            },
        ),
    ]
