# Generated by Django 5.1.1 on 2024-09-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentDormitory', '0003_staff_alter_room_options_remove_student_number_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dutyschedule',
            name='room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='floor',
        ),
        migrations.AlterField(
            model_name='repairrequests',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус заявки'),
        ),
    ]
