# Generated by Django 5.1.1 on 2024-09-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentDormitory', '0004_remove_dutyschedule_room_remove_room_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='picture',
            field=models.ImageField(null=True, upload_to='staff', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='student',
            name='picture',
            field=models.ImageField(null=True, upload_to='students', verbose_name='Изображение'),
        ),
    ]
